//  ssdt_category.dart
//  Created by JeoJay127
//
import 'package:rapidssdt/utils/ssdttool/table.dart';

class SsdtCategory {
  static const patchCategories = [
    {
      'name': 'corePatches',
      'remark': 'corePatchesRemark',
      'actions': [
        ACPITable.ssdtHPET,
        ACPITable.ssdtECUSBXDesktop,
        ACPITable.ssdtECUSBXLaptop,
        ACPITable.ssdtECDesktop,
        ACPITable.ssdtECLaptop,
        ACPITable.ssdtUSBX,
        ACPITable.ssdtPLUG,
        ACPITable.ssdtPMC,
        ACPITable.ssdtAWAC,
        ACPITable.ssdtRTC0RANGE,
      ],
    },
    {
      'name': 'functionPatches',
      'remark': 'functionPatchesRemark',
      'actions': [
        ACPITable.ssdtPNLF,
        ACPITable.ssdtALS0,
        ACPITable.ssdtXOSI,
        ACPITable.ssdtRHUB,
        ACPITable.ssdtBridge,
        ACPITable.ssdtDMAR,
        ACPITable.ssdtSBUSMCHC,
        ACPITable.ssdtIMEI,
        ACPITable.ssdtFixShutdown,
        ACPITable.ssdtGPRW,
        ACPITable.ssdtUPRW,
        ACPITable.ssdtFACP,
        ACPITable.ssdtRMNE,
        ACPITable.ssdtGPI0,
      ],
    },
    {
      'name': 'devicePatches',
      'remark': 'devicePatchesRemark',
      'actions': [
        ACPITable.ssdtGPUSPOOF,
        ACPITable.ssdtPCIDISABLE,
      ],
    },
    {
      'name': 'specialPatches',
      'remark': 'specialPatchesRemark',
      'actions': [
        ACPITable.ssdtAPIC,
        ACPITable.ssdtIMEI,
        ACPITable.ssdtUNC,
        ACPITable.ssdtRTC0RANGE,
        ACPITable.ssdtCPUR,
      ],
    },
    {
      'name': 'sleepPatches',
      'remark': 'sleepPatchesRemark',
      'actions': [
        ACPITable.checkSystemState,
        ACPITable.checkAOAC,
        ACPITable.ssdtGPRW,
        ACPITable.ssdtUPRW,
        ACPITable.ssdtLID,
        ACPITable.ssdtWakeScreen,
        ACPITable.ssdtLED,
        ACPITable.ssdtS3Disable,
        ACPITable.ssdtPWRB,
        ACPITable.ssdtSLPB,
      ],
    },
    {
      'name': 'auxiliaryPatches',
      'remark': 'auxiliaryPatchesRemark',
      'actions': [
        ACPITable.ssdtDTGP,
        ACPITable.ssdtDMAC,
        ACPITable.ssdtMEM2,
      ],
    },
    {
      'name': 'prebuiltPatches',
      'actions': [
        ACPITable.ssdtECDesktop,
        ACPITable.ssdtECLaptop,
        ACPITable.ssdtECUSBXDesktop,
        ACPITable.ssdtECUSBXLaptop,
        ACPITable.ssdtPLUG,
        ACPITable.ssdtPLUGALT,
        ACPITable.ssdtAWAC,
        ACPITable.ssdtPMC,
        ACPITable.ssdtPNLF,
        ACPITable.ssdtIMEI,
        ACPITable.ssdtXOSI,
        ACPITable.ssdtALS0,
        ACPITable.ssdtCPUR,
        ACPITable.ssdtRHUB,
        ACPITable.ssdtUNC,
        ACPITable.ssdtRTC0RANGE,
        ACPITable.ssdtFixShutdown,
        ACPITable.ssdtSBUSMCHC,
        ACPITable.ssdtRMNE,
        ACPITable.ssdtGPI0,
        ACPITable.ssdtS3Disable,
        ACPITable.ssdtGPRW,
        ACPITable.ssdtUPRW,
        ACPITable.ssdtDTGP,
        ACPITable.ssdtDMAC,
        ACPITable.ssdtPWRB,
        ACPITable.ssdtSLPB,
        ACPITable.ssdtMEM2,
      ],
    },
  ];
}
